package net.minecraft.server.v1_8_R3;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import java.lang.reflect.Type;
import net.minecraft.server.v1_8_R3.BiomeBase;
import net.minecraft.server.v1_8_R3.ChatDeserializer;

public class CustomWorldSettingsFinal {
   public final float a;
   public final float b;
   public final float c;
   public final float d;
   public final float e;
   public final float f;
   public final float g;
   public final float h;
   public final float i;
   public final float j;
   public final float k;
   public final float l;
   public final float m;
   public final float n;
   public final float o;
   public final float p;
   public final int q;
   public final boolean r;
   public final boolean s;
   public final int t;
   public final boolean u;
   public final boolean v;
   public final boolean w;
   public final boolean x;
   public final boolean y;
   public final boolean z;
   public final boolean A;
   public final int B;
   public final boolean C;
   public final int D;
   public final boolean E;
   public final int F;
   public final int G;
   public final int H;
   public final int I;
   public final int J;
   public final int K;
   public final int L;
   public final int M;
   public final int N;
   public final int O;
   public final int P;
   public final int Q;
   public final int R;
   public final int S;
   public final int T;
   public final int U;
   public final int V;
   public final int W;
   public final int X;
   public final int Y;
   public final int Z;
   public final int aa;
   public final int ab;
   public final int ac;
   public final int ad;
   public final int ae;
   public final int af;
   public final int ag;
   public final int ah;
   public final int ai;
   public final int aj;
   public final int ak;
   public final int al;
   public final int am;
   public final int an;
   public final int ao;
   public final int ap;
   public final int aq;
   public final int ar;
   public final int as;
   public final int at;
   public final int au;
   public final int av;
   public final int aw;
   public final int ax;
   public final int ay;
   public final int az;

   private CustomWorldSettingsFinal(CustomWorldSettingsFinal.CustomWorldSettings p_i681_1_) {
      this.a = p_i681_1_.b;
      this.b = p_i681_1_.c;
      this.c = p_i681_1_.d;
      this.d = p_i681_1_.e;
      this.e = p_i681_1_.f;
      this.f = p_i681_1_.g;
      this.g = p_i681_1_.h;
      this.h = p_i681_1_.i;
      this.i = p_i681_1_.j;
      this.j = p_i681_1_.k;
      this.k = p_i681_1_.l;
      this.l = p_i681_1_.m;
      this.m = p_i681_1_.n;
      this.n = p_i681_1_.o;
      this.o = p_i681_1_.p;
      this.p = p_i681_1_.q;
      this.q = p_i681_1_.r;
      this.r = p_i681_1_.s;
      this.s = p_i681_1_.t;
      this.t = p_i681_1_.u;
      this.u = p_i681_1_.v;
      this.v = p_i681_1_.w;
      this.w = p_i681_1_.x;
      this.x = p_i681_1_.y;
      this.y = p_i681_1_.z;
      this.z = p_i681_1_.A;
      this.A = p_i681_1_.B;
      this.B = p_i681_1_.C;
      this.C = p_i681_1_.D;
      this.D = p_i681_1_.E;
      this.E = p_i681_1_.F;
      this.F = p_i681_1_.G;
      this.G = p_i681_1_.H;
      this.H = p_i681_1_.I;
      this.I = p_i681_1_.J;
      this.J = p_i681_1_.K;
      this.K = p_i681_1_.L;
      this.L = p_i681_1_.M;
      this.M = p_i681_1_.N;
      this.N = p_i681_1_.O;
      this.O = p_i681_1_.P;
      this.P = p_i681_1_.Q;
      this.Q = p_i681_1_.R;
      this.R = p_i681_1_.S;
      this.S = p_i681_1_.T;
      this.T = p_i681_1_.U;
      this.U = p_i681_1_.V;
      this.V = p_i681_1_.W;
      this.W = p_i681_1_.X;
      this.X = p_i681_1_.Y;
      this.Y = p_i681_1_.Z;
      this.Z = p_i681_1_.aa;
      this.aa = p_i681_1_.ab;
      this.ab = p_i681_1_.ac;
      this.ac = p_i681_1_.ad;
      this.ad = p_i681_1_.ae;
      this.ae = p_i681_1_.af;
      this.af = p_i681_1_.ag;
      this.ag = p_i681_1_.ah;
      this.ah = p_i681_1_.ai;
      this.ai = p_i681_1_.aj;
      this.aj = p_i681_1_.ak;
      this.ak = p_i681_1_.al;
      this.al = p_i681_1_.am;
      this.am = p_i681_1_.an;
      this.an = p_i681_1_.ao;
      this.ao = p_i681_1_.ap;
      this.ap = p_i681_1_.aq;
      this.aq = p_i681_1_.ar;
      this.ar = p_i681_1_.as;
      this.as = p_i681_1_.at;
      this.at = p_i681_1_.au;
      this.au = p_i681_1_.av;
      this.av = p_i681_1_.aw;
      this.aw = p_i681_1_.ax;
      this.ax = p_i681_1_.ay;
      this.ay = p_i681_1_.az;
      this.az = p_i681_1_.aA;
   }

   public static class CustomWorldSettings {
      static final Gson a = (new GsonBuilder()).registerTypeAdapter(CustomWorldSettingsFinal.CustomWorldSettings.class, new CustomWorldSettingsFinal.CustomWorldSettingsSerializer()).create();
      public float b = 684.412F;
      public float c = 684.412F;
      public float d = 512.0F;
      public float e = 512.0F;
      public float f = 200.0F;
      public float g = 200.0F;
      public float h = 0.5F;
      public float i = 80.0F;
      public float j = 160.0F;
      public float k = 80.0F;
      public float l = 8.5F;
      public float m = 12.0F;
      public float n = 1.0F;
      public float o = 0.0F;
      public float p = 1.0F;
      public float q = 0.0F;
      public int r = 63;
      public boolean s = true;
      public boolean t = true;
      public int u = 8;
      public boolean v = true;
      public boolean w = true;
      public boolean x = true;
      public boolean y = true;
      public boolean z = true;
      public boolean A = true;
      public boolean B = true;
      public int C = 4;
      public boolean D = true;
      public int E = 80;
      public boolean F = false;
      public int G = -1;
      public int H = 4;
      public int I = 4;
      public int J = 33;
      public int K = 10;
      public int L = 0;
      public int M = 256;
      public int N = 33;
      public int O = 8;
      public int P = 0;
      public int Q = 256;
      public int R = 33;
      public int S = 10;
      public int T = 0;
      public int U = 80;
      public int V = 33;
      public int W = 10;
      public int X = 0;
      public int Y = 80;
      public int Z = 33;
      public int aa = 10;
      public int ab = 0;
      public int ac = 80;
      public int ad = 17;
      public int ae = 20;
      public int af = 0;
      public int ag = 128;
      public int ah = 9;
      public int ai = 20;
      public int aj = 0;
      public int ak = 64;
      public int al = 9;
      public int am = 2;
      public int an = 0;
      public int ao = 32;
      public int ap = 8;
      public int aq = 8;
      public int ar = 0;
      public int as = 16;
      public int at = 8;
      public int au = 1;
      public int av = 0;
      public int aw = 16;
      public int ax = 7;
      public int ay = 1;
      public int az = 16;
      public int aA = 16;

      public static CustomWorldSettingsFinal.CustomWorldSettings a(String p_a_0_) {
         if(p_a_0_.length() == 0) {
            return new CustomWorldSettingsFinal.CustomWorldSettings();
         } else {
            try {
               return (CustomWorldSettingsFinal.CustomWorldSettings)a.fromJson(p_a_0_, CustomWorldSettingsFinal.CustomWorldSettings.class);
            } catch (Exception var2) {
               return new CustomWorldSettingsFinal.CustomWorldSettings();
            }
         }
      }

      public String toString() {
         return a.toJson((Object)this);
      }

      public CustomWorldSettings() {
         this.a();
      }

      public void a() {
         this.b = 684.412F;
         this.c = 684.412F;
         this.d = 512.0F;
         this.e = 512.0F;
         this.f = 200.0F;
         this.g = 200.0F;
         this.h = 0.5F;
         this.i = 80.0F;
         this.j = 160.0F;
         this.k = 80.0F;
         this.l = 8.5F;
         this.m = 12.0F;
         this.n = 1.0F;
         this.o = 0.0F;
         this.p = 1.0F;
         this.q = 0.0F;
         this.r = 63;
         this.s = true;
         this.t = true;
         this.u = 8;
         this.v = true;
         this.w = true;
         this.x = true;
         this.y = true;
         this.z = true;
         this.A = true;
         this.B = true;
         this.C = 4;
         this.D = true;
         this.E = 80;
         this.F = false;
         this.G = -1;
         this.H = 4;
         this.I = 4;
         this.J = 33;
         this.K = 10;
         this.L = 0;
         this.M = 256;
         this.N = 33;
         this.O = 8;
         this.P = 0;
         this.Q = 256;
         this.R = 33;
         this.S = 10;
         this.T = 0;
         this.U = 80;
         this.V = 33;
         this.W = 10;
         this.X = 0;
         this.Y = 80;
         this.Z = 33;
         this.aa = 10;
         this.ab = 0;
         this.ac = 80;
         this.ad = 17;
         this.ae = 20;
         this.af = 0;
         this.ag = 128;
         this.ah = 9;
         this.ai = 20;
         this.aj = 0;
         this.ak = 64;
         this.al = 9;
         this.am = 2;
         this.an = 0;
         this.ao = 32;
         this.ap = 8;
         this.aq = 8;
         this.ar = 0;
         this.as = 16;
         this.at = 8;
         this.au = 1;
         this.av = 0;
         this.aw = 16;
         this.ax = 7;
         this.ay = 1;
         this.az = 16;
         this.aA = 16;
      }

      public boolean equals(Object p_equals_1_) {
         if(this == p_equals_1_) {
            return true;
         } else if(p_equals_1_ != null && this.getClass() == p_equals_1_.getClass()) {
            CustomWorldSettingsFinal.CustomWorldSettings customworldsettingsfinal$customworldsettings = (CustomWorldSettingsFinal.CustomWorldSettings)p_equals_1_;
            return this.aa != customworldsettingsfinal$customworldsettings.aa?false:(this.ac != customworldsettingsfinal$customworldsettings.ac?false:(this.ab != customworldsettingsfinal$customworldsettings.ab?false:(this.Z != customworldsettingsfinal$customworldsettings.Z?false:(Float.compare(customworldsettingsfinal$customworldsettings.l, this.l) != 0?false:(Float.compare(customworldsettingsfinal$customworldsettings.o, this.o) != 0?false:(Float.compare(customworldsettingsfinal$customworldsettings.n, this.n) != 0?false:(Float.compare(customworldsettingsfinal$customworldsettings.q, this.q) != 0?false:(Float.compare(customworldsettingsfinal$customworldsettings.p, this.p) != 0?false:(this.H != customworldsettingsfinal$customworldsettings.H?false:(this.ae != customworldsettingsfinal$customworldsettings.ae?false:(this.ag != customworldsettingsfinal$customworldsettings.ag?false:(this.af != customworldsettingsfinal$customworldsettings.af?false:(this.ad != customworldsettingsfinal$customworldsettings.ad?false:(Float.compare(customworldsettingsfinal$customworldsettings.b, this.b) != 0?false:(Float.compare(customworldsettingsfinal$customworldsettings.h, this.h) != 0?false:(Float.compare(customworldsettingsfinal$customworldsettings.f, this.f) != 0?false:(Float.compare(customworldsettingsfinal$customworldsettings.g, this.g) != 0?false:(this.au != customworldsettingsfinal$customworldsettings.au?false:(this.aw != customworldsettingsfinal$customworldsettings.aw?false:(this.av != customworldsettingsfinal$customworldsettings.av?false:(this.at != customworldsettingsfinal$customworldsettings.at?false:(this.W != customworldsettingsfinal$customworldsettings.W?false:(this.Y != customworldsettingsfinal$customworldsettings.Y?false:(this.X != customworldsettingsfinal$customworldsettings.X?false:(this.V != customworldsettingsfinal$customworldsettings.V?false:(this.K != customworldsettingsfinal$customworldsettings.K?false:(this.M != customworldsettingsfinal$customworldsettings.M?false:(this.L != customworldsettingsfinal$customworldsettings.L?false:(this.J != customworldsettingsfinal$customworldsettings.J?false:(this.u != customworldsettingsfinal$customworldsettings.u?false:(this.G != customworldsettingsfinal$customworldsettings.G?false:(this.am != customworldsettingsfinal$customworldsettings.am?false:(this.ao != customworldsettingsfinal$customworldsettings.ao?false:(this.an != customworldsettingsfinal$customworldsettings.an?false:(this.al != customworldsettingsfinal$customworldsettings.al?false:(this.S != customworldsettingsfinal$customworldsettings.S?false:(this.U != customworldsettingsfinal$customworldsettings.U?false:(this.T != customworldsettingsfinal$customworldsettings.T?false:(this.R != customworldsettingsfinal$customworldsettings.R?false:(this.O != customworldsettingsfinal$customworldsettings.O?false:(this.Q != customworldsettingsfinal$customworldsettings.Q?false:(this.P != customworldsettingsfinal$customworldsettings.P?false:(this.N != customworldsettingsfinal$customworldsettings.N?false:(Float.compare(customworldsettingsfinal$customworldsettings.c, this.c) != 0?false:(this.ai != customworldsettingsfinal$customworldsettings.ai?false:(this.ak != customworldsettingsfinal$customworldsettings.ak?false:(this.aj != customworldsettingsfinal$customworldsettings.aj?false:(this.ah != customworldsettingsfinal$customworldsettings.ah?false:(this.az != customworldsettingsfinal$customworldsettings.az?false:(this.ay != customworldsettingsfinal$customworldsettings.ay?false:(this.ax != customworldsettingsfinal$customworldsettings.ax?false:(this.aA != customworldsettingsfinal$customworldsettings.aA?false:(this.E != customworldsettingsfinal$customworldsettings.E?false:(Float.compare(customworldsettingsfinal$customworldsettings.e, this.e) != 0?false:(Float.compare(customworldsettingsfinal$customworldsettings.i, this.i) != 0?false:(Float.compare(customworldsettingsfinal$customworldsettings.j, this.j) != 0?false:(Float.compare(customworldsettingsfinal$customworldsettings.k, this.k) != 0?false:(this.aq != customworldsettingsfinal$customworldsettings.aq?false:(this.as != customworldsettingsfinal$customworldsettings.as?false:(this.ar != customworldsettingsfinal$customworldsettings.ar?false:(this.ap != customworldsettingsfinal$customworldsettings.ap?false:(this.I != customworldsettingsfinal$customworldsettings.I?false:(this.r != customworldsettingsfinal$customworldsettings.r?false:(Float.compare(customworldsettingsfinal$customworldsettings.m, this.m) != 0?false:(Float.compare(customworldsettingsfinal$customworldsettings.d, this.d) != 0?false:(this.s != customworldsettingsfinal$customworldsettings.s?false:(this.t != customworldsettingsfinal$customworldsettings.t?false:(this.D != customworldsettingsfinal$customworldsettings.D?false:(this.F != customworldsettingsfinal$customworldsettings.F?false:(this.x != customworldsettingsfinal$customworldsettings.x?false:(this.A != customworldsettingsfinal$customworldsettings.A?false:(this.v != customworldsettingsfinal$customworldsettings.v?false:(this.y != customworldsettingsfinal$customworldsettings.y?false:(this.z != customworldsettingsfinal$customworldsettings.z?false:(this.w != customworldsettingsfinal$customworldsettings.w?false:(this.B != customworldsettingsfinal$customworldsettings.B?false:this.C == customworldsettingsfinal$customworldsettings.C))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
         } else {
            return false;
         }
      }

      public int hashCode() {
         int ix = this.b != 0.0F?Float.floatToIntBits(this.b):0;
         ix = 31 * ix + (this.c != 0.0F?Float.floatToIntBits(this.c):0);
         ix = 31 * ix + (this.d != 0.0F?Float.floatToIntBits(this.d):0);
         ix = 31 * ix + (this.e != 0.0F?Float.floatToIntBits(this.e):0);
         ix = 31 * ix + (this.f != 0.0F?Float.floatToIntBits(this.f):0);
         ix = 31 * ix + (this.g != 0.0F?Float.floatToIntBits(this.g):0);
         ix = 31 * ix + (this.h != 0.0F?Float.floatToIntBits(this.h):0);
         ix = 31 * ix + (this.i != 0.0F?Float.floatToIntBits(this.i):0);
         ix = 31 * ix + (this.j != 0.0F?Float.floatToIntBits(this.j):0);
         ix = 31 * ix + (this.k != 0.0F?Float.floatToIntBits(this.k):0);
         ix = 31 * ix + (this.l != 0.0F?Float.floatToIntBits(this.l):0);
         ix = 31 * ix + (this.m != 0.0F?Float.floatToIntBits(this.m):0);
         ix = 31 * ix + (this.n != 0.0F?Float.floatToIntBits(this.n):0);
         ix = 31 * ix + (this.o != 0.0F?Float.floatToIntBits(this.o):0);
         ix = 31 * ix + (this.p != 0.0F?Float.floatToIntBits(this.p):0);
         ix = 31 * ix + (this.q != 0.0F?Float.floatToIntBits(this.q):0);
         ix = 31 * ix + this.r;
         ix = 31 * ix + (this.s?1:0);
         ix = 31 * ix + (this.t?1:0);
         ix = 31 * ix + this.u;
         ix = 31 * ix + (this.v?1:0);
         ix = 31 * ix + (this.w?1:0);
         ix = 31 * ix + (this.x?1:0);
         ix = 31 * ix + (this.y?1:0);
         ix = 31 * ix + (this.z?1:0);
         ix = 31 * ix + (this.A?1:0);
         ix = 31 * ix + (this.B?1:0);
         ix = 31 * ix + this.C;
         ix = 31 * ix + (this.D?1:0);
         ix = 31 * ix + this.E;
         ix = 31 * ix + (this.F?1:0);
         ix = 31 * ix + this.G;
         ix = 31 * ix + this.H;
         ix = 31 * ix + this.I;
         ix = 31 * ix + this.J;
         ix = 31 * ix + this.K;
         ix = 31 * ix + this.L;
         ix = 31 * ix + this.M;
         ix = 31 * ix + this.N;
         ix = 31 * ix + this.O;
         ix = 31 * ix + this.P;
         ix = 31 * ix + this.Q;
         ix = 31 * ix + this.R;
         ix = 31 * ix + this.S;
         ix = 31 * ix + this.T;
         ix = 31 * ix + this.U;
         ix = 31 * ix + this.V;
         ix = 31 * ix + this.W;
         ix = 31 * ix + this.X;
         ix = 31 * ix + this.Y;
         ix = 31 * ix + this.Z;
         ix = 31 * ix + this.aa;
         ix = 31 * ix + this.ab;
         ix = 31 * ix + this.ac;
         ix = 31 * ix + this.ad;
         ix = 31 * ix + this.ae;
         ix = 31 * ix + this.af;
         ix = 31 * ix + this.ag;
         ix = 31 * ix + this.ah;
         ix = 31 * ix + this.ai;
         ix = 31 * ix + this.aj;
         ix = 31 * ix + this.ak;
         ix = 31 * ix + this.al;
         ix = 31 * ix + this.am;
         ix = 31 * ix + this.an;
         ix = 31 * ix + this.ao;
         ix = 31 * ix + this.ap;
         ix = 31 * ix + this.aq;
         ix = 31 * ix + this.ar;
         ix = 31 * ix + this.as;
         ix = 31 * ix + this.at;
         ix = 31 * ix + this.au;
         ix = 31 * ix + this.av;
         ix = 31 * ix + this.aw;
         ix = 31 * ix + this.ax;
         ix = 31 * ix + this.ay;
         ix = 31 * ix + this.az;
         ix = 31 * ix + this.aA;
         return ix;
      }

      public CustomWorldSettingsFinal b() {
         return new CustomWorldSettingsFinal(this);
      }
   }

   public static class CustomWorldSettingsSerializer implements JsonDeserializer<CustomWorldSettingsFinal.CustomWorldSettings>, JsonSerializer<CustomWorldSettingsFinal.CustomWorldSettings> {
      public CustomWorldSettingsFinal.CustomWorldSettings a(JsonElement p_a_1_, Type p_a_2_, JsonDeserializationContext p_a_3_) throws JsonParseException {
         JsonObject jsonobject = p_a_1_.getAsJsonObject();
         CustomWorldSettingsFinal.CustomWorldSettings customworldsettingsfinal$customworldsettings = new CustomWorldSettingsFinal.CustomWorldSettings();

         try {
            customworldsettingsfinal$customworldsettings.b = ChatDeserializer.a(jsonobject, "coordinateScale", customworldsettingsfinal$customworldsettings.b);
            customworldsettingsfinal$customworldsettings.c = ChatDeserializer.a(jsonobject, "heightScale", customworldsettingsfinal$customworldsettings.c);
            customworldsettingsfinal$customworldsettings.e = ChatDeserializer.a(jsonobject, "lowerLimitScale", customworldsettingsfinal$customworldsettings.e);
            customworldsettingsfinal$customworldsettings.d = ChatDeserializer.a(jsonobject, "upperLimitScale", customworldsettingsfinal$customworldsettings.d);
            customworldsettingsfinal$customworldsettings.f = ChatDeserializer.a(jsonobject, "depthNoiseScaleX", customworldsettingsfinal$customworldsettings.f);
            customworldsettingsfinal$customworldsettings.g = ChatDeserializer.a(jsonobject, "depthNoiseScaleZ", customworldsettingsfinal$customworldsettings.g);
            customworldsettingsfinal$customworldsettings.h = ChatDeserializer.a(jsonobject, "depthNoiseScaleExponent", customworldsettingsfinal$customworldsettings.h);
            customworldsettingsfinal$customworldsettings.i = ChatDeserializer.a(jsonobject, "mainNoiseScaleX", customworldsettingsfinal$customworldsettings.i);
            customworldsettingsfinal$customworldsettings.j = ChatDeserializer.a(jsonobject, "mainNoiseScaleY", customworldsettingsfinal$customworldsettings.j);
            customworldsettingsfinal$customworldsettings.k = ChatDeserializer.a(jsonobject, "mainNoiseScaleZ", customworldsettingsfinal$customworldsettings.k);
            customworldsettingsfinal$customworldsettings.l = ChatDeserializer.a(jsonobject, "baseSize", customworldsettingsfinal$customworldsettings.l);
            customworldsettingsfinal$customworldsettings.m = ChatDeserializer.a(jsonobject, "stretchY", customworldsettingsfinal$customworldsettings.m);
            customworldsettingsfinal$customworldsettings.n = ChatDeserializer.a(jsonobject, "biomeDepthWeight", customworldsettingsfinal$customworldsettings.n);
            customworldsettingsfinal$customworldsettings.o = ChatDeserializer.a(jsonobject, "biomeDepthOffset", customworldsettingsfinal$customworldsettings.o);
            customworldsettingsfinal$customworldsettings.p = ChatDeserializer.a(jsonobject, "biomeScaleWeight", customworldsettingsfinal$customworldsettings.p);
            customworldsettingsfinal$customworldsettings.q = ChatDeserializer.a(jsonobject, "biomeScaleOffset", customworldsettingsfinal$customworldsettings.q);
            customworldsettingsfinal$customworldsettings.r = ChatDeserializer.a(jsonobject, "seaLevel", customworldsettingsfinal$customworldsettings.r);
            customworldsettingsfinal$customworldsettings.s = ChatDeserializer.a(jsonobject, "useCaves", customworldsettingsfinal$customworldsettings.s);
            customworldsettingsfinal$customworldsettings.t = ChatDeserializer.a(jsonobject, "useDungeons", customworldsettingsfinal$customworldsettings.t);
            customworldsettingsfinal$customworldsettings.u = ChatDeserializer.a(jsonobject, "dungeonChance", customworldsettingsfinal$customworldsettings.u);
            customworldsettingsfinal$customworldsettings.v = ChatDeserializer.a(jsonobject, "useStrongholds", customworldsettingsfinal$customworldsettings.v);
            customworldsettingsfinal$customworldsettings.w = ChatDeserializer.a(jsonobject, "useVillages", customworldsettingsfinal$customworldsettings.w);
            customworldsettingsfinal$customworldsettings.x = ChatDeserializer.a(jsonobject, "useMineShafts", customworldsettingsfinal$customworldsettings.x);
            customworldsettingsfinal$customworldsettings.y = ChatDeserializer.a(jsonobject, "useTemples", customworldsettingsfinal$customworldsettings.y);
            customworldsettingsfinal$customworldsettings.z = ChatDeserializer.a(jsonobject, "useMonuments", customworldsettingsfinal$customworldsettings.z);
            customworldsettingsfinal$customworldsettings.A = ChatDeserializer.a(jsonobject, "useRavines", customworldsettingsfinal$customworldsettings.A);
            customworldsettingsfinal$customworldsettings.B = ChatDeserializer.a(jsonobject, "useWaterLakes", customworldsettingsfinal$customworldsettings.B);
            customworldsettingsfinal$customworldsettings.C = ChatDeserializer.a(jsonobject, "waterLakeChance", customworldsettingsfinal$customworldsettings.C);
            customworldsettingsfinal$customworldsettings.D = ChatDeserializer.a(jsonobject, "useLavaLakes", customworldsettingsfinal$customworldsettings.D);
            customworldsettingsfinal$customworldsettings.E = ChatDeserializer.a(jsonobject, "lavaLakeChance", customworldsettingsfinal$customworldsettings.E);
            customworldsettingsfinal$customworldsettings.F = ChatDeserializer.a(jsonobject, "useLavaOceans", customworldsettingsfinal$customworldsettings.F);
            customworldsettingsfinal$customworldsettings.G = ChatDeserializer.a(jsonobject, "fixedBiome", customworldsettingsfinal$customworldsettings.G);
            if(customworldsettingsfinal$customworldsettings.G < 38 && customworldsettingsfinal$customworldsettings.G >= -1) {
               if(customworldsettingsfinal$customworldsettings.G >= BiomeBase.HELL.id) {
                  customworldsettingsfinal$customworldsettings.G += 2;
               }
            } else {
               customworldsettingsfinal$customworldsettings.G = -1;
            }

            customworldsettingsfinal$customworldsettings.H = ChatDeserializer.a(jsonobject, "biomeSize", customworldsettingsfinal$customworldsettings.H);
            customworldsettingsfinal$customworldsettings.I = ChatDeserializer.a(jsonobject, "riverSize", customworldsettingsfinal$customworldsettings.I);
            customworldsettingsfinal$customworldsettings.J = ChatDeserializer.a(jsonobject, "dirtSize", customworldsettingsfinal$customworldsettings.J);
            customworldsettingsfinal$customworldsettings.K = ChatDeserializer.a(jsonobject, "dirtCount", customworldsettingsfinal$customworldsettings.K);
            customworldsettingsfinal$customworldsettings.L = ChatDeserializer.a(jsonobject, "dirtMinHeight", customworldsettingsfinal$customworldsettings.L);
            customworldsettingsfinal$customworldsettings.M = ChatDeserializer.a(jsonobject, "dirtMaxHeight", customworldsettingsfinal$customworldsettings.M);
            customworldsettingsfinal$customworldsettings.N = ChatDeserializer.a(jsonobject, "gravelSize", customworldsettingsfinal$customworldsettings.N);
            customworldsettingsfinal$customworldsettings.O = ChatDeserializer.a(jsonobject, "gravelCount", customworldsettingsfinal$customworldsettings.O);
            customworldsettingsfinal$customworldsettings.P = ChatDeserializer.a(jsonobject, "gravelMinHeight", customworldsettingsfinal$customworldsettings.P);
            customworldsettingsfinal$customworldsettings.Q = ChatDeserializer.a(jsonobject, "gravelMaxHeight", customworldsettingsfinal$customworldsettings.Q);
            customworldsettingsfinal$customworldsettings.R = ChatDeserializer.a(jsonobject, "graniteSize", customworldsettingsfinal$customworldsettings.R);
            customworldsettingsfinal$customworldsettings.S = ChatDeserializer.a(jsonobject, "graniteCount", customworldsettingsfinal$customworldsettings.S);
            customworldsettingsfinal$customworldsettings.T = ChatDeserializer.a(jsonobject, "graniteMinHeight", customworldsettingsfinal$customworldsettings.T);
            customworldsettingsfinal$customworldsettings.U = ChatDeserializer.a(jsonobject, "graniteMaxHeight", customworldsettingsfinal$customworldsettings.U);
            customworldsettingsfinal$customworldsettings.V = ChatDeserializer.a(jsonobject, "dioriteSize", customworldsettingsfinal$customworldsettings.V);
            customworldsettingsfinal$customworldsettings.W = ChatDeserializer.a(jsonobject, "dioriteCount", customworldsettingsfinal$customworldsettings.W);
            customworldsettingsfinal$customworldsettings.X = ChatDeserializer.a(jsonobject, "dioriteMinHeight", customworldsettingsfinal$customworldsettings.X);
            customworldsettingsfinal$customworldsettings.Y = ChatDeserializer.a(jsonobject, "dioriteMaxHeight", customworldsettingsfinal$customworldsettings.Y);
            customworldsettingsfinal$customworldsettings.Z = ChatDeserializer.a(jsonobject, "andesiteSize", customworldsettingsfinal$customworldsettings.Z);
            customworldsettingsfinal$customworldsettings.aa = ChatDeserializer.a(jsonobject, "andesiteCount", customworldsettingsfinal$customworldsettings.aa);
            customworldsettingsfinal$customworldsettings.ab = ChatDeserializer.a(jsonobject, "andesiteMinHeight", customworldsettingsfinal$customworldsettings.ab);
            customworldsettingsfinal$customworldsettings.ac = ChatDeserializer.a(jsonobject, "andesiteMaxHeight", customworldsettingsfinal$customworldsettings.ac);
            customworldsettingsfinal$customworldsettings.ad = ChatDeserializer.a(jsonobject, "coalSize", customworldsettingsfinal$customworldsettings.ad);
            customworldsettingsfinal$customworldsettings.ae = ChatDeserializer.a(jsonobject, "coalCount", customworldsettingsfinal$customworldsettings.ae);
            customworldsettingsfinal$customworldsettings.af = ChatDeserializer.a(jsonobject, "coalMinHeight", customworldsettingsfinal$customworldsettings.af);
            customworldsettingsfinal$customworldsettings.ag = ChatDeserializer.a(jsonobject, "coalMaxHeight", customworldsettingsfinal$customworldsettings.ag);
            customworldsettingsfinal$customworldsettings.ah = ChatDeserializer.a(jsonobject, "ironSize", customworldsettingsfinal$customworldsettings.ah);
            customworldsettingsfinal$customworldsettings.ai = ChatDeserializer.a(jsonobject, "ironCount", customworldsettingsfinal$customworldsettings.ai);
            customworldsettingsfinal$customworldsettings.aj = ChatDeserializer.a(jsonobject, "ironMinHeight", customworldsettingsfinal$customworldsettings.aj);
            customworldsettingsfinal$customworldsettings.ak = ChatDeserializer.a(jsonobject, "ironMaxHeight", customworldsettingsfinal$customworldsettings.ak);
            customworldsettingsfinal$customworldsettings.al = ChatDeserializer.a(jsonobject, "goldSize", customworldsettingsfinal$customworldsettings.al);
            customworldsettingsfinal$customworldsettings.am = ChatDeserializer.a(jsonobject, "goldCount", customworldsettingsfinal$customworldsettings.am);
            customworldsettingsfinal$customworldsettings.an = ChatDeserializer.a(jsonobject, "goldMinHeight", customworldsettingsfinal$customworldsettings.an);
            customworldsettingsfinal$customworldsettings.ao = ChatDeserializer.a(jsonobject, "goldMaxHeight", customworldsettingsfinal$customworldsettings.ao);
            customworldsettingsfinal$customworldsettings.ap = ChatDeserializer.a(jsonobject, "redstoneSize", customworldsettingsfinal$customworldsettings.ap);
            customworldsettingsfinal$customworldsettings.aq = ChatDeserializer.a(jsonobject, "redstoneCount", customworldsettingsfinal$customworldsettings.aq);
            customworldsettingsfinal$customworldsettings.ar = ChatDeserializer.a(jsonobject, "redstoneMinHeight", customworldsettingsfinal$customworldsettings.ar);
            customworldsettingsfinal$customworldsettings.as = ChatDeserializer.a(jsonobject, "redstoneMaxHeight", customworldsettingsfinal$customworldsettings.as);
            customworldsettingsfinal$customworldsettings.at = ChatDeserializer.a(jsonobject, "diamondSize", customworldsettingsfinal$customworldsettings.at);
            customworldsettingsfinal$customworldsettings.au = ChatDeserializer.a(jsonobject, "diamondCount", customworldsettingsfinal$customworldsettings.au);
            customworldsettingsfinal$customworldsettings.av = ChatDeserializer.a(jsonobject, "diamondMinHeight", customworldsettingsfinal$customworldsettings.av);
            customworldsettingsfinal$customworldsettings.aw = ChatDeserializer.a(jsonobject, "diamondMaxHeight", customworldsettingsfinal$customworldsettings.aw);
            customworldsettingsfinal$customworldsettings.ax = ChatDeserializer.a(jsonobject, "lapisSize", customworldsettingsfinal$customworldsettings.ax);
            customworldsettingsfinal$customworldsettings.ay = ChatDeserializer.a(jsonobject, "lapisCount", customworldsettingsfinal$customworldsettings.ay);
            customworldsettingsfinal$customworldsettings.az = ChatDeserializer.a(jsonobject, "lapisCenterHeight", customworldsettingsfinal$customworldsettings.az);
            customworldsettingsfinal$customworldsettings.aA = ChatDeserializer.a(jsonobject, "lapisSpread", customworldsettingsfinal$customworldsettings.aA);
         } catch (Exception var7) {
            ;
         }

         return customworldsettingsfinal$customworldsettings;
      }

      public JsonElement a(CustomWorldSettingsFinal.CustomWorldSettings p_a_1_, Type p_a_2_, JsonSerializationContext p_a_3_) {
         JsonObject jsonobject = new JsonObject();
         jsonobject.addProperty("coordinateScale", (Number)Float.valueOf(p_a_1_.b));
         jsonobject.addProperty("heightScale", (Number)Float.valueOf(p_a_1_.c));
         jsonobject.addProperty("lowerLimitScale", (Number)Float.valueOf(p_a_1_.e));
         jsonobject.addProperty("upperLimitScale", (Number)Float.valueOf(p_a_1_.d));
         jsonobject.addProperty("depthNoiseScaleX", (Number)Float.valueOf(p_a_1_.f));
         jsonobject.addProperty("depthNoiseScaleZ", (Number)Float.valueOf(p_a_1_.g));
         jsonobject.addProperty("depthNoiseScaleExponent", (Number)Float.valueOf(p_a_1_.h));
         jsonobject.addProperty("mainNoiseScaleX", (Number)Float.valueOf(p_a_1_.i));
         jsonobject.addProperty("mainNoiseScaleY", (Number)Float.valueOf(p_a_1_.j));
         jsonobject.addProperty("mainNoiseScaleZ", (Number)Float.valueOf(p_a_1_.k));
         jsonobject.addProperty("baseSize", (Number)Float.valueOf(p_a_1_.l));
         jsonobject.addProperty("stretchY", (Number)Float.valueOf(p_a_1_.m));
         jsonobject.addProperty("biomeDepthWeight", (Number)Float.valueOf(p_a_1_.n));
         jsonobject.addProperty("biomeDepthOffset", (Number)Float.valueOf(p_a_1_.o));
         jsonobject.addProperty("biomeScaleWeight", (Number)Float.valueOf(p_a_1_.p));
         jsonobject.addProperty("biomeScaleOffset", (Number)Float.valueOf(p_a_1_.q));
         jsonobject.addProperty("seaLevel", (Number)Integer.valueOf(p_a_1_.r));
         jsonobject.addProperty("useCaves", Boolean.valueOf(p_a_1_.s));
         jsonobject.addProperty("useDungeons", Boolean.valueOf(p_a_1_.t));
         jsonobject.addProperty("dungeonChance", (Number)Integer.valueOf(p_a_1_.u));
         jsonobject.addProperty("useStrongholds", Boolean.valueOf(p_a_1_.v));
         jsonobject.addProperty("useVillages", Boolean.valueOf(p_a_1_.w));
         jsonobject.addProperty("useMineShafts", Boolean.valueOf(p_a_1_.x));
         jsonobject.addProperty("useTemples", Boolean.valueOf(p_a_1_.y));
         jsonobject.addProperty("useMonuments", Boolean.valueOf(p_a_1_.z));
         jsonobject.addProperty("useRavines", Boolean.valueOf(p_a_1_.A));
         jsonobject.addProperty("useWaterLakes", Boolean.valueOf(p_a_1_.B));
         jsonobject.addProperty("waterLakeChance", (Number)Integer.valueOf(p_a_1_.C));
         jsonobject.addProperty("useLavaLakes", Boolean.valueOf(p_a_1_.D));
         jsonobject.addProperty("lavaLakeChance", (Number)Integer.valueOf(p_a_1_.E));
         jsonobject.addProperty("useLavaOceans", Boolean.valueOf(p_a_1_.F));
         jsonobject.addProperty("fixedBiome", (Number)Integer.valueOf(p_a_1_.G));
         jsonobject.addProperty("biomeSize", (Number)Integer.valueOf(p_a_1_.H));
         jsonobject.addProperty("riverSize", (Number)Integer.valueOf(p_a_1_.I));
         jsonobject.addProperty("dirtSize", (Number)Integer.valueOf(p_a_1_.J));
         jsonobject.addProperty("dirtCount", (Number)Integer.valueOf(p_a_1_.K));
         jsonobject.addProperty("dirtMinHeight", (Number)Integer.valueOf(p_a_1_.L));
         jsonobject.addProperty("dirtMaxHeight", (Number)Integer.valueOf(p_a_1_.M));
         jsonobject.addProperty("gravelSize", (Number)Integer.valueOf(p_a_1_.N));
         jsonobject.addProperty("gravelCount", (Number)Integer.valueOf(p_a_1_.O));
         jsonobject.addProperty("gravelMinHeight", (Number)Integer.valueOf(p_a_1_.P));
         jsonobject.addProperty("gravelMaxHeight", (Number)Integer.valueOf(p_a_1_.Q));
         jsonobject.addProperty("graniteSize", (Number)Integer.valueOf(p_a_1_.R));
         jsonobject.addProperty("graniteCount", (Number)Integer.valueOf(p_a_1_.S));
         jsonobject.addProperty("graniteMinHeight", (Number)Integer.valueOf(p_a_1_.T));
         jsonobject.addProperty("graniteMaxHeight", (Number)Integer.valueOf(p_a_1_.U));
         jsonobject.addProperty("dioriteSize", (Number)Integer.valueOf(p_a_1_.V));
         jsonobject.addProperty("dioriteCount", (Number)Integer.valueOf(p_a_1_.W));
         jsonobject.addProperty("dioriteMinHeight", (Number)Integer.valueOf(p_a_1_.X));
         jsonobject.addProperty("dioriteMaxHeight", (Number)Integer.valueOf(p_a_1_.Y));
         jsonobject.addProperty("andesiteSize", (Number)Integer.valueOf(p_a_1_.Z));
         jsonobject.addProperty("andesiteCount", (Number)Integer.valueOf(p_a_1_.aa));
         jsonobject.addProperty("andesiteMinHeight", (Number)Integer.valueOf(p_a_1_.ab));
         jsonobject.addProperty("andesiteMaxHeight", (Number)Integer.valueOf(p_a_1_.ac));
         jsonobject.addProperty("coalSize", (Number)Integer.valueOf(p_a_1_.ad));
         jsonobject.addProperty("coalCount", (Number)Integer.valueOf(p_a_1_.ae));
         jsonobject.addProperty("coalMinHeight", (Number)Integer.valueOf(p_a_1_.af));
         jsonobject.addProperty("coalMaxHeight", (Number)Integer.valueOf(p_a_1_.ag));
         jsonobject.addProperty("ironSize", (Number)Integer.valueOf(p_a_1_.ah));
         jsonobject.addProperty("ironCount", (Number)Integer.valueOf(p_a_1_.ai));
         jsonobject.addProperty("ironMinHeight", (Number)Integer.valueOf(p_a_1_.aj));
         jsonobject.addProperty("ironMaxHeight", (Number)Integer.valueOf(p_a_1_.ak));
         jsonobject.addProperty("goldSize", (Number)Integer.valueOf(p_a_1_.al));
         jsonobject.addProperty("goldCount", (Number)Integer.valueOf(p_a_1_.am));
         jsonobject.addProperty("goldMinHeight", (Number)Integer.valueOf(p_a_1_.an));
         jsonobject.addProperty("goldMaxHeight", (Number)Integer.valueOf(p_a_1_.ao));
         jsonobject.addProperty("redstoneSize", (Number)Integer.valueOf(p_a_1_.ap));
         jsonobject.addProperty("redstoneCount", (Number)Integer.valueOf(p_a_1_.aq));
         jsonobject.addProperty("redstoneMinHeight", (Number)Integer.valueOf(p_a_1_.ar));
         jsonobject.addProperty("redstoneMaxHeight", (Number)Integer.valueOf(p_a_1_.as));
         jsonobject.addProperty("diamondSize", (Number)Integer.valueOf(p_a_1_.at));
         jsonobject.addProperty("diamondCount", (Number)Integer.valueOf(p_a_1_.au));
         jsonobject.addProperty("diamondMinHeight", (Number)Integer.valueOf(p_a_1_.av));
         jsonobject.addProperty("diamondMaxHeight", (Number)Integer.valueOf(p_a_1_.aw));
         jsonobject.addProperty("lapisSize", (Number)Integer.valueOf(p_a_1_.ax));
         jsonobject.addProperty("lapisCount", (Number)Integer.valueOf(p_a_1_.ay));
         jsonobject.addProperty("lapisCenterHeight", (Number)Integer.valueOf(p_a_1_.az));
         jsonobject.addProperty("lapisSpread", (Number)Integer.valueOf(p_a_1_.aA));
         return jsonobject;
      }
   }
}
